[build]
publish = "_site"

[build.environment]
NODE_VERSION = "18"   # or another stable version you prefer

[[plugins]]
package = "@quarto/netlify-plugin-quarto"

  [plugins.inputs]
  version = "1.7.29"
