[build]
publish = "_site"          # where Quarto outputs the HTML

[[plugins]]
package = "@quarto/netlify-plugin-quarto"

  [plugins.inputs]
  version = "1.7.29"       # same Quarto version you use locally
